name: SPDR Bot Auto Update

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

permissions:
  contents: write 

jobs:
  Cap-nhat-Du-Lieu:
    runs-on: ubuntu-latest
    
    steps:
      - name: Bước 1 - Mở kho chứa
        uses: actions/checkout@v4

      - name: Bước 2 - Thiết lập môi trường Python ảo
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Bước 3 - Cài đặt thư viện (Đồ nghề)
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests openpyxl yfinance

      - name: Bước 4 - Khởi động Hệ thống Bot Đa Luồng
        run: |
          python Bot_SPDR.py
          python Bot_OTHER_ETFs.py

      - name: Bước 5 - Đóng gói và Lưu Dữ liệu lên Đám mây
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add .
          git commit -m "V2 Nâng cấp: Chuẩn hóa tên cột Date, hold, ton, usd_flow" || echo "Không có dữ liệu mới"
          git pull --rebase origin main
          git push
