name: SPDR Bot Auto Update

on:
  schedule:
    # 00:00 giờ UTC tương đương với 07:00 sáng giờ Việt Nam
    - cron: '0 0 * * *' 
  workflow_dispatch: # Tính năng này cho phép bạn bấm nút chạy thử bằng tay lúc nào cũng được

permissions:
  contents: write # Cấp quyền cho Robot được phép lưu file CSV mới vào kho chứa

jobs:
  Cap-nhat-Du-Lieu:
    runs-on: ubuntu-latest
    steps:
      - name: Bước 1 - Mở kho chứa
        uses: actions/checkout@v3

      - name: Bước 2 - Chuẩn bị máy tính ảo (Python 3.11)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Bước 3 - Lấy đồ nghề (Cài thư viện)
        run: pip install pandas requests openpyxl

      - name: Bước 4 - Chạy Bot SPDR
        run: python Bot_SPDR.py

      - name: Bước 5 - Đóng gói và lưu file CSV lên GitHub
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add SPDR_Data_MT5.csv
          git commit -m "Bot tự động cập nhật dữ liệu SPDR" -a || echo "Không có dữ liệu mới để lưu"
          git push
